import type { Vehicle } from "./vehicle.types";

export const FLEET_VEHICLES: Vehicle[] = [
  {
    id: "veh-01",
    slug: "maruti-swift-dzire",
    name: "Maruti Swift Dzire",
    category: "sedan",
    seats: 5,
    fuelTypes: ["Petrol", "CNG", "Diesel"],
    features: [
      "Air Conditioning",
      "Compact Sedan",
      "Budget Friendly",
      "Music System",
      "Ample Boot Space",
    ],
    recommendedFor: [
      "Small Family Trips",
      "Local Pick-up & Drop",
      "City Commute",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/swift-dzire.svg",
    gallery: ["/assets/vehicles/placeholders/swift-dzire.svg"],
    sortOrder: 1,
  },
  {
    id: "veh-02",
    slug: "hyundai-aura",
    name: "Hyundai Aura",
    category: "sedan",
    seats: 5,
    fuelTypes: ["CNG"],
    features: [
      "Air Conditioning",
      "High Fuel Efficiency",
      "Comfort Sedan",
      "Modern Ergonomics",
    ],
    recommendedFor: ["Outstation Trips", "Daily Rentals", "Executive Pick-up"],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/hyundai-aura.svg",
    gallery: ["/assets/vehicles/placeholders/hyundai-aura.svg"],
    sortOrder: 2,
  },
  {
    id: "veh-03",
    slug: "maruti-ertiga",
    name: "Maruti Ertiga",
    category: "muv",
    seats: 7,
    fuelTypes: ["Petrol", "CNG"],
    features: [
      "Air Conditioning",
      "Flexible Seating",
      "Spacious Cabin",
      "Family MUV",
    ],
    recommendedFor: [
      "Family Outstation Travel",
      "Weekend Getaways",
      "Group Outings",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/maruti-ertiga.svg",
    gallery: ["/assets/vehicles/placeholders/maruti-ertiga.svg"],
    sortOrder: 3,
  },
  {
    id: "veh-04",
    slug: "toyota-innova-crysta",
    name: "Toyota Innova Crysta",
    category: "muv",
    seats: 8,
    fuelTypes: ["Diesel"],
    features: [
      "Dual-Zone AC",
      "Premium Leather Seats",
      "Executive Comfort",
      "Long Distance Suspension",
    ],
    recommendedFor: [
      "Long Distance Outstation",
      "Executive Corporate Travel",
      "VIP Guests",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/innova-crysta.svg",
    gallery: ["/assets/vehicles/placeholders/innova-crysta.svg"],
    sortOrder: 4,
  },
  {
    id: "veh-05",
    slug: "force-toofan-cruiser",
    name: "Force Toofan Cruiser",
    category: "muv",
    seats: 11,
    fuelTypes: ["Diesel"],
    features: [
      "High Seating Capacity",
      "Multi-Utility Vehicle",
      "Heavy Duty Engine",
      "Group Seating",
    ],
    recommendedFor: [
      "Large Family Tours",
      "Pilgrimage Journeys",
      "Rural & Highway Travel",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/force-toofan.svg",
    gallery: ["/assets/vehicles/placeholders/force-toofan.svg"],
    sortOrder: 5,
  },
  {
    id: "veh-06",
    slug: "mahindra-scorpio",
    name: "Mahindra Scorpio",
    category: "suv",
    seats: 7,
    fuelTypes: ["Diesel"],
    features: [
      "High Ground Clearance",
      "Tough SUV Body",
      "Powerful Diesel Engine",
      "All-Terrain Capability",
    ],
    recommendedFor: [
      "Outstation Adventures",
      "Rough Terrain Travel",
      "Family Tours",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/mahindra-scorpio.svg",
    gallery: ["/assets/vehicles/placeholders/mahindra-scorpio.svg"],
    sortOrder: 6,
  },
  {
    id: "veh-07",
    slug: "mahindra-bolero",
    name: "Mahindra Bolero",
    category: "suv",
    seats: 7,
    fuelTypes: ["Diesel"],
    features: [
      "Heavy-Duty Construction",
      "Rugged SUV Design",
      "High Reliability",
      "Rural Terrain Expert",
    ],
    recommendedFor: [
      "Rural & Outstation Journeys",
      "Event Support",
      "Heavy Luggage Trips",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/mahindra-bolero.svg",
    gallery: ["/assets/vehicles/placeholders/mahindra-bolero.svg"],
    sortOrder: 7,
  },
  {
    id: "veh-08",
    slug: "maruti-brezza",
    name: "Maruti Brezza",
    category: "suv",
    seats: 5,
    fuelTypes: ["Petrol", "CNG"],
    features: [
      "Compact SUV",
      "Air Conditioning",
      "Urban Navigation",
      "Comfort Ride",
    ],
    recommendedFor: [
      "City Navigation",
      "Short Outstation Trips",
      "Corporate Commute",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/maruti-brezza.svg",
    gallery: ["/assets/vehicles/placeholders/maruti-brezza.svg"],
    sortOrder: 8,
  },
  {
    id: "veh-09",
    slug: "maruti-grand-vitara",
    name: "Maruti Grand Vitara",
    category: "suv",
    seats: 5,
    fuelTypes: ["Petrol", "CNG"],
    features: [
      "Mid-Size Luxury SUV",
      "Premium Interiors",
      "Smooth Ride Quality",
      "Advanced Ergonomics",
    ],
    recommendedFor: ["Business Trips", "Luxury Outstation", "VIP Commute"],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/grand-vitara.svg",
    gallery: ["/assets/vehicles/placeholders/grand-vitara.svg"],
    sortOrder: 9,
  },
  {
    id: "veh-10",
    slug: "mahindra-thar",
    name: "Mahindra Thar",
    category: "suv",
    seats: 5,
    fuelTypes: ["Diesel"],
    features: [
      "4x4 Off-Road SUV",
      "Iconic Rugged Styling",
      "Adventure Build",
      "High Stance",
    ],
    recommendedFor: [
      "Off-Road Adventures",
      "Style & Event Travel",
      "Special Occasions",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/mahindra-thar.svg",
    gallery: ["/assets/vehicles/placeholders/mahindra-thar.svg"],
    sortOrder: 10,
  },
  {
    id: "veh-11",
    slug: "tempo-traveller",
    name: "Tempo Traveller",
    category: "minibus",
    seats: 13,
    fuelTypes: ["Diesel"],
    features: [
      "Chauffeur-Driven Coach",
      "Pushback Seats",
      "Ample Luggage Space",
      "AC / Music System",
    ],
    recommendedFor: [
      "Group Tour Coach",
      "Corporate Outings",
      "Wedding Guest Transport",
    ],
    availability: "available",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/tempo-traveller.svg",
    gallery: ["/assets/vehicles/placeholders/tempo-traveller.svg"],
    sortOrder: 11,
  },
  {
    id: "veh-12",
    slug: "25-seater-bus",
    name: "25-Seater Bus",
    category: "bus",
    seats: 25,
    fuelTypes: ["Diesel"],
    features: [
      "Large Group Coach",
      "AC / Non-AC Options",
      "Reclining Seats",
      "Heavy Commercial Chassis",
    ],
    recommendedFor: [
      "Marriage Ceremonies",
      "Large Corporate Events",
      "Interstate Group Pilgrimages",
    ],
    availability: "booked",
    chauffeurIncluded: true,
    image: "/assets/vehicles/placeholders/25-seater-bus.svg",
    gallery: ["/assets/vehicles/placeholders/25-seater-bus.svg"],
    sortOrder: 12,
  },
];
